[package]
name = "jsonom"
version = "0.1.1"
edition = "2021"

[dependencies]
nom = "7.1.3"
tracing = "0.1.37"

[dev-dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
